/*
 * PoleDisplay.java
 *
 * Created on March 4, 2008, 8:58 AM
 */
package api;

import api.VideoPlayerPanelAPI;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import org.apache.log4j.LogManager;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Angelo
 */
public class PoleDisplayAPI extends javax.swing.JFrame implements
        WindowFocusListener, Runnable {

    static Logger log = LogManager.getLogger(PoleDisplayAPI.class.getName());
    /**
     * Creates new form PoleDisplay
     */
    public PoleDisplayAPI() {
        setUndecorated(true);
        initComponents();
        
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        this.addWindowFocusListener(this);
    }

    public void StartMovie() {
        Greeter.setVisible(false);
        log.info("Initializing Pole Display");
        log.info("Loading Default Pole Display Movie");
        vidPanel1.VideoPlay("file://C://JTerminals/effects/sssigsc.avi");
        vidPanel1.setBounds(0, -45, 820, 615);
        this.add(vidPanel1);
        vidPanel1.setVisible(true);
        this.setComponentZOrder(vidPanel1, getComponentCount());
        new ADClock();
        new ClearPlate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displayDate = new javax.swing.JLabel();
        displayTime = new javax.swing.JLabel();
        lblToday1 = new javax.swing.JLabel();
        lblToday2 = new javax.swing.JLabel();
        SlotsNo = new javax.swing.JLabel();
        lblSlotsNo = new javax.swing.JLabel();
        lblPlateDisplay = new javax.swing.JLabel();
        Contact = new javax.swing.JLabel();
        PlsPay = new javax.swing.JLabel();
        lblComeAgain = new javax.swing.JLabel();
        AD1 = new javax.swing.JLabel();
        Greeter = new javax.swing.JLabel();
        VIPS = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        PlateNo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        displayDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        displayDate.setForeground(new java.awt.Color(51, 204, 0));
        displayDate.setText("_");
        jPanel1.add(displayDate);
        displayDate.setBounds(550, 0, 140, 22);

        displayTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        displayTime.setForeground(new java.awt.Color(51, 204, 0));
        displayTime.setText("_");
        jPanel1.add(displayTime);
        displayTime.setBounds(550, 30, 140, 22);

        lblToday1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblToday1.setForeground(new java.awt.Color(51, 51, 255));
        lblToday1.setText("Date:");
        jPanel1.add(lblToday1);
        lblToday1.setBounds(490, 0, 50, 22);

        lblToday2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblToday2.setForeground(new java.awt.Color(51, 51, 255));
        lblToday2.setText("Time:");
        jPanel1.add(lblToday2);
        lblToday2.setBounds(490, 30, 51, 22);

        SlotsNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SlotsNo.setForeground(new java.awt.Color(0, 153, 0));
        SlotsNo.setText("125");
        jPanel1.add(SlotsNo);
        SlotsNo.setBounds(160, 12, 110, 30);

        lblSlotsNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSlotsNo.setForeground(new java.awt.Color(51, 51, 255));
        lblSlotsNo.setText("Available Slots:");
        jPanel1.add(lblSlotsNo);
        lblSlotsNo.setBounds(10, 20, 136, 22);

        lblPlateDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPlateDisplay.setForeground(new java.awt.Color(51, 51, 255));
        lblPlateDisplay.setText("Plate Number:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(1024, 0, 800, 600));
        setForeground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        Contact.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Contact.setForeground(new java.awt.Color(255, 255, 255));
        Contact.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Contact.setText("Contact Kim Binas 7533480");
        Contact.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(Contact);
        Contact.setBounds(0, 490, 780, 26);

        PlsPay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PlsPay.setForeground(new java.awt.Color(255, 255, 255));
        PlsPay.setText("Please Pay : ");
        getContentPane().add(PlsPay);
        PlsPay.setBounds(18, 490, 370, 20);

        lblComeAgain.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblComeAgain.setForeground(new java.awt.Color(242, 195, 36));
        lblComeAgain.setText("Thank You Come Again");
        getContentPane().add(lblComeAgain);
        lblComeAgain.setBounds(398, 580, 240, 22);

        AD1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        AD1.setForeground(new java.awt.Color(255, 255, 102));
        AD1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AD1.setText("Place your AD here");
        AD1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        AD1.setMaximumSize(new java.awt.Dimension(800, 78));
        AD1.setMinimumSize(new java.awt.Dimension(800, 78));
        AD1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(AD1);
        AD1.setBounds(0, 426, 800, 80);

        Greeter.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Greeter.setForeground(new java.awt.Color(255, 255, 0));
        Greeter.setText("Have A Pleasant Day,");
        getContentPane().add(Greeter);
        Greeter.setBounds(80, 210, 330, 40);

        VIPS.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        VIPS.setForeground(new java.awt.Color(255, 255, 0));
        VIPS.setText("_");
        VIPS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(VIPS);
        VIPS.setBounds(170, 210, 520, 100);
        VIPS.getAccessibleContext().setAccessibleName("Vips");

        BG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BG.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BG.setMaximumSize(new java.awt.Dimension(800, 400));
        BG.setMinimumSize(new java.awt.Dimension(800, 400));
        BG.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(BG);
        BG.setBounds(0, 0, 1000, 600);

        PlateNo.setFont(new java.awt.Font("Tahoma", 1, 85)); // NOI18N
        PlateNo.setForeground(new java.awt.Color(0, 255, 0));
        PlateNo.setText(".");
        PlateNo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(PlateNo);
        PlateNo.setBounds(10, 500, 510, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PoleDisplayAPI().setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AD1;
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Contact;
    public javax.swing.JLabel Greeter;
    public javax.swing.JLabel PlateNo;
    public javax.swing.JLabel PlsPay;
    public javax.swing.JLabel SlotsNo;
    public javax.swing.JLabel VIPS;
    public javax.swing.JLabel displayDate;
    public javax.swing.JLabel displayTime;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblComeAgain;
    private javax.swing.JLabel lblPlateDisplay;
    private javax.swing.JLabel lblSlotsNo;
    private javax.swing.JLabel lblToday1;
    private javax.swing.JLabel lblToday2;
    // End of variables declaration//GEN-END:variables
    public VideoPlayerPanelAPI vidPanel1 = new VideoPlayerPanelAPI();
    public int thirtysecs = 0;
    private String staticplate = "";

    class ADClock implements Runnable {

        String PicADS[] = new String[10];

        ADClock() {
            PicADS[0] = "/hybrid/resources/theatermall.jpg";
            PicADS[1] = "/hybrid/resources/coke_zero.jpg";
            PicADS[2] = "/hybrid/resources/displayPOS.jpg";
            PicADS[3] = "/hybrid/resources/shoppesville.jpg";

            Thread dc = new Thread(this);
            dc.start();
        }

        @Override
        public void run() {
            try {
                while (true) {
                    //System.out.print("." + vidPanel1.isValid());
                    switch (thirtysecs) {
                        case 1:
                        case 2:
                        case 3:
                        case 4:
                        case 5:
                            BG.setIcon(new javax.swing.ImageIcon(getClass().getResource(PicADS[3])));
                            break;
                        case 6:
                        case 7:
                        case 8:
                        case 9:
                        case 10:
                            BG.setIcon(new javax.swing.ImageIcon(getClass().getResource(PicADS[2])));
                            break;
                        case 11:
                        case 12:
                        case 13:
                        case 14:
                        case 15:
                            BG.setIcon(new javax.swing.ImageIcon(getClass().getResource(PicADS[1])));
                            break;
                        case 16:
                        case 17:
                        case 18:
                        case 19:
                        case 20:
                            BG.setIcon(new javax.swing.ImageIcon(getClass().getResource(PicADS[0])));
                            break;
                        case 21:
                        case 22:
                        case 23:
                        case 24:
                        case 25:
                        case 26:
                        case 27:
                        case 28:
                        case 29:
                        case 30:
                            vidPanel1.VideoPlay("file://C://JTerminals/effects/sssigsc.avi");
                            //vidPanel1.mediaPlayer1.stop();
                            vidPanel1.setVisible(true);
                            thirtysecs = 0;
                            PlateNo.setText("");
                            BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hybrid/resources/theatermall.jpg")));
                            break;
                    }
                    thirtysecs = thirtysecs + 1;
                    PlateNo.setLocation(thirtysecs * 20, 500);
                    Thread.sleep(1000);
                }
            } catch (Exception ex) {
                log.error(ex.getMessage());
            }
        }

    }

    class ClearPlate implements Runnable {

        ClearPlate() {
            Thread dc = new Thread(this);
            dc.start();
        }

        @Override
        public void run() {
            try {
                while (true) {
                    staticplate = PlateNo.getText();
                    Thread.sleep(30000);
                    if (staticplate.compareToIgnoreCase(PlateNo.getText()) == 0) {
                        PlateNo.setText("");
                    } else {
                        Thread.sleep(30000);
                    }
                }
            } catch (Exception ex) {
                log.error(ex.getMessage());
            }
        }

    }

    @Override
    public void windowGainedFocus(WindowEvent e) {
        this.trapExit();
    }

    @Override
    public void windowLostFocus(WindowEvent e) {
        this.trapExit();
    }

    private void trapExit() {
        //this.setAlwaysOnTop(false); 
        //this.toBack();
    }

    @Override
    public void run() {
        try {
            Thread.sleep(15000);
            StartMovie();
        } catch (InterruptedException ex) {
            log.error(ex.getMessage());
        }
    }
}
