/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misc;

/**
 *
 * @author theor
 */
public class HEXConverter {
    public String charToHex(char base) {
        switch (base) {
            case '-':
                return "00";
            case ' ':
                return "20";
            case '!':
                return "21";
            case '"':
                return "22";
            case '#':
                return "23";
            case '$':
                return "24";
            case '0':
                return "30";
            case '1':
                return "31";
            case '2':
                return "32";
            case '3':
                return "33";
            case '4':
                return "34";
            case '5':
                return "35";
            case '6':
                return "36";
            case '7':
                return "37";
            case '8':
                return "38";
            case '9':
                return "39";
            case ':':
                return "3A";
            case ';':
                return "3B";
            case '<':
                return "3C";
            case '=':
                return "3D";
            case '>':
                return "3E";
            case '?':
                return "3F";
            case '@':
                return "40";
            case 'A':
                return "41";
            case 'B':
                return "42";
            case 'C':
                return "43";
            case 'D':
                return "44";
            case 'E':
                return "45";
            case 'F':
                return "46";
            case 'G':
                return "47";
            case 'H':
                return "48";
            case 'I':
                return "49";
            case 'J':
                return "4A";
            case 'K':
                return "4B";
            case 'L':
                return "4C";
            case 'M':
                return "4D";
            case 'N':
                return "4E";
            case 'O':
                return "4F";
            case 'P':
                return "50";
            case 'Q':
                return "51";
            case 'R':
                return "52";
            case 'S':
                return "53";
            case 'T':
                return "54";
            case 'U':
                return "55";
            case 'V':
                return "56";
            case 'W':
                return "57";
            case 'X':
                return "58";
            case 'Y':
                return "59";
            case 'Z':
                return "5A";
                
                //small char
                
            case 'a':
                return "61";
            case 'b':
                return "62";
            case 'c':
                return "63";
            case 'd':
                return "64";
            case 'e':
                return "65";
            case 'f':
                return "66";
            case 'g':
                return "67";
            case 'h':
                return "68";
            case 'i':
                return "69";
            case 'j':
                return "6A";
            case 'k':
                return "6B";
            case 'l':
                return "6C";
            case 'm':
                return "6D";
            case 'n':
                return "6E";
            case 'o':
                return "6F";
            case 'p':
                return "70";
            case 'q':
                return "71";
            case 'r':
                return "72";
            case 's':
                return "73";
            case 't':
                return "74";
            case 'u':
                return "75";
            case 'v':
                return "76";
            case 'w':
                return "77";
            case 'x':
                return "78";
            case 'y':
                return "79";
            case 'z':
                return "7A";
        }
        return "";
    }
    
    public String hexToStr(String base) {
        switch (base) {
            case "00":
                return "-";
            case "20":
                return " ";
            case "21":
                return "!" ;
            case "22":
                return "\"";
            case "23":
                return "#";
            case "24":
                return "$";
            case "30":
                return "0";
            case "31":
                return "1";
            case "32":
                return "2";
            case "33":
                return "3";
            case "34":
                return "4";
            case "35":
                return "5";
            case "36":
                return "6";
            case "37":
                return "7";
            case "38":
                return "8";
            case "39":
                return "9";
            case "3A":
                return ":";
            case "3B":
                return ";";
            case "3C":
                return "<";
            case "3D":
                return "=";
            case "3E":
                return ">";
            case "3F":
                return "?";
            case "40":
                return "@";
            case "41":
                return "A";
            case "42":
                return "B";
            case "43":
                return "C";
            case "44":
                return "D";
            case "45":
                return "E";
            case "46":
                return "F";
            case "47":
                return "G";
            case "48":
                return "H";
            case "49":
                return "I";
            case "4A":
                return "J";
            case "4B":
                return "K";
            case "4C":
                return "L";
            case "4D":
                return "M";
            case "4E":
                return "N";
            case "4F":
                return "O";
            case "50":
                return "P";
            case "51":
                return "Q";
            case "52":
                return "R";
            case "53":
                return "S";
            case "54":
                return "T";
            case "55":
                return "U";
            case "56":
                return "V";
            case "57":
                return "W";
            case "58":
                return "X";
            case "59":
                return "Y";
            case "5A":
                return "Z";
                
                //small char
                
            case "61":
                return "a";
            case "62":
                return "b";
            case "63":
                return "c";
            case "64":
                return "d";
            case "65":
                return "e";
            case "66":
                return "f";
            case "67":
                return "g";
            case "68":
                return "h";
            case "69":
                return "i";
            case "6A":
                return "j";
            case "6B":
                return "k";
            case "6C":
                return "l";
            case "6D":
                return "m";
            case "6E":
                return "n";
            case "6F":
                return "o";
            case "70":
                return "p";
            case "71":
                return "q";
            case "72":
                return "r";
            case "73":
                return "s";
            case "74":
                return "t";
            case "75":
                return "u";
            case "76":
                return "v";
            case "77":
                return "w";
            case "78":
                return "x";
            case "79":
                return "y";
            case "7A":
                return "z";
        }
        return "";
    }
    
}
